### PR TITLE
SVCPLAN-5555: Add support for SUSE

### PR DESCRIPTION
**Pull request by billglick**
This is being tested on `control-test-opensuse155a`.

### CODE REVIEW

**Review by jakerundall — APPROVED** [review]
Looks good. I'm seeing pdk update/validate changes and the addition of Suse OS data.

**Comment by jakerundall** [comment]
I guess I should note that I can't ssh as rundall from cerberus3 to control-test-opensuse155a.internal.ncsa.edu, but the proximate cause is that rundall is not recognized, probably due to an issue with sssd.

**Comment by billglick** [comment]
After fixing the sssd issue, users still cannot ssh into this test host using a password. GSSAPI auth using kerberos works for users to authenticated, but password seems to be broken. I'm guessing this is an issue either with PAM and/or SSHd.

**Comment by billglick** [comment]
The ssh issues were not a result of this profile_pam_access (and have been fixed).

**Pull request merged**
