### PR TITLE
ASDPLNG-48: Review puppet-profile_pam_access

### PR DESCRIPTION
**Pull request by billglick**
I had overlooked reviewing this. Since we are including in the base profile in the control-repo, we should review it.

The changes here are mostly from:
- adding CI actions
- cleaning up yaml data
- upgrading the version of pdk

There should be no changes to core functionality of this shared profile (i.e. none of the manifest files changes).

### CODE REVIEW

**Comment by billglick** [comment]
This has been tested on both glick-pup.ncsa.illinois.edu & glick-client01.ncsa.illinois.edu via the 'topic/asdplng48' branch of https://github.com/ncsa/control-repo.

**Review by andylytical — COMMENTED** [review]
Can you fix these yamllint warnings?
```
./.github/workflows/pdk-validate.yml
  3:1       warning  truthy value should be one of [false, true]  (truthy)

./.github/workflows/yamllint.yml
  3:1       warning  truthy value should be one of [false, true]  (truthy)
```

@bsper2 What was the workaround we decided on when you ran into this?

**Comment by bsper2** [comment]
The fix for the warnings for both those files is to setup line 3 so it reads:
`on:  # yamllint disable-line rule:truthy
`

Since they are just warnings, the yamllint action won't flag is as failed which is why it's given it a pass. To set things more strict so that even warnings trigger a failure from yamllint you want to add a `strict:"true"`, so the whole config for .github/workflows/yamllint.yml ends up looking like:
```
---
name: "yamllint"
on:  # yamllint disable-line rule:truthy
  - "push"
  - "pull_request"
jobs:
  lintAllTheThings:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v1"
      - name: "yaml-lint"
        uses: "ibiqlik/action-yamllint@v3"
        with:
          strict: "true"
```

Can grab the full configs for both the CI checks from the wiki here:
https://wiki.ncsa.illinois.edu/display/PUPPET/Add+continuous+integration+%28CI%29+testing+to+a+repo

**Comment by billglick** [comment]
I had missed that we had updated the configs for the CI actions. I’ve been copying them from other profiles. But I’ll update those CI files tomorrow.

**Comment by billglick** [comment]
Does anyone want to do any more review of this before I merge it?

**Review by bsper2 — APPROVED** [review]
Looks good to me.

**Pull request merged**
